name: GHA Build

on:
    push:
     branches:
      - main
    workflow_dispatch:

jobs:
  
  test:
    runs-on: ubuntu-latest
    #needs: [build]   # Depends on 'build' job
    steps:
      - name: Run tests
        run: echo "Running Tests..."

      - name: Checkout to Collect Test Results
        uses: actions/checkout@v3

      - name: Publish Test Results in Cloudbees Plaform
        uses: cloudbees-io-gha/publish-test-results@main
        with:
          test-type: GO
          results-path: test_reports/*
          cloudbees-pat: ${{ secrets.CBP_PAT_PROD }}
          
      - name: Publish evidence
        uses: cloudbees-io-gha/publish-evidence-item@main
        with:
          cloudbees-pat: ${{ secrets.CBP_PAT_PROD }}
          content: |-
            Testing Completed and results published to Cloudbees platform
            Test | Results |
            --------|---------|
            Test 1 | PASS |
            Test 2 | FAIL |
            Test 3 | PASS |


  deploy:
    runs-on: ubuntu-latest
    needs: [test]   # Depends on both 'build' and 'test' jobs
    steps:
      - name: Checkout to Prepare Manifest
        uses: actions/checkout@v3
        
      - name: Trigger Deployment
        uses: cloudbees-io-gha/run-cloudbees-workflow@main
        id: deploy
        with :
          cloudbees-pat: ${{ secrets.CBP_PAT_PROD }}
          workflow-file-name: "cbp-deploy.yaml"
          workflow-inputs: '{"artifactName": "SampleApp-Backend","artifactVersion": "2.0.0", "environment": "qa"}'

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.deploy.outputs.cbp_run_url}}"


