name: GHA Label artifact
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  label-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: label-artifact
        uses: cloudbees-io-gha/label-artifact-version@v1
        with:
          artifact-id: 6bfa2b11-5087-4305-a142-de7e9798c965
          labels: Stable,Release candidate
          operation: ADD
